### ISSUE TITLE
Does not work with the most recent Visual Studio

### ISSUE THREAD

**Issue by mleotta** [Kitware/qtextensions#20]
Building against QtExtensions with recent Visual Studio fails because of this line:

https://github.com/Kitware/qtextensions/blob/master/core/qtGlobal.h#L18

`_MSC_VER` is now greater than `1914` and causes this code to complain.  Can we remove the upper bounds on the version?

**Comment by mwoehlke-kitware** [comment]
The intent is to tell the compiler to [stop lying about `__cplusplus`](https://docs.microsoft.com/en-us/cpp/build/reference/zc-cplusplus). I'm not sure if the best way to handle this is to export that as a usage requirement, or to teach CMake to understand it as part of the language standard level (see also https://gitlab.kitware.com/cmake/cmake/issues/18837).
